kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
kubeadmConfigPatches:
- |-
  kind: ClusterConfiguration
  controllerManager:
    extraArgs:
      bind-address: 0.0.0.0 #Disable localhost binding
      secure-port: "0"      #Disable the https 
      port: "10257"         #Enable http on port 10257
  etcd:
    local:
      extraArgs:
        listen-metrics-urls: http://0.0.0.0:2381
  scheduler:
    extraArgs:
      bind-address: 0.0.0.0  #Disable localhost binding
      secure-port: "0"       #Disable the https
      port: "10259"          #Enable http on port 10259
- |-
  kind: KubeProxyConfiguration
  metricsBindAddress: 0.0.0.0
nodes:
- role: control-plane
- role: worker
  labels:
    ingress : worker
  extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      protocol: TCP
- role: worker
- role: worker
